<?php
//官方彩
		$apiurls = [
			'actkeno'  => '/api.open.kj.code.actkeno',
			'bjkeno'   => '自行看说明修复使用?type=bjkeno',
			'jndkeno'  => '/api.open.kj.code.jndkeno',
			'hgkeno'   => '/api.open.kj.code.hgkeno',
			'twkeno'   => '/api.open.kj.code.twkeno',
			'cqssc'    => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=cqssc&rows=20&format=json',
			'xjssc'    => '自行看说明修复使用?type=xjssc',
			'tjssc'    => '自行看说明修复使用?type=tjssc',
			'dfssc'    => '/api.open.kj.code.dfssc',
			'df11x5'    => '/api.open.kj.code.df11x5',
			//--------------------------K3---------------------------------
			'nmgk3'    => '自行看说明修复使用?type=nmgk3',
			'hebk3'    => '自行看说明修复使用?type=hebk3',
			'bjk3'     => '自行看说明修复使用?type=bjk3',
			'shk3'     => '自行看说明修复使用?type=shk3',
			'jsk3'     => '自行看说明修复使用?type=jsk3',
			'jlk3'     => '自行看说明修复使用?type=jlk3',
			'ahk3'     => '自行看说明修复使用?type=ahk3',
			'gxk3'     => '自行看说明修复使用?type=gxk3',
			'gsk3'     => '自行看说明修复使用?type=gsk3',
			'hubk3'    => '自行看说明修复使用?type=hubk3',
			'jxk3'     => '自行看说明修复使用?type=jxk3',
			'fjk3'		=> '自行看说明修复使用?type=fjk3',
			'nmgk3'		=> '自行看说明修复使用?type=nmgk3',
			'gzk3'		=> '自行看说明修复使用?type=gzk3',
			'jsk3'		=> '自行看说明修复使用?type=jsk3',
			'qhk3'		=> '自行看说明修复使用?type=qhk3',
			'henk3'		=> '自行看说明修复使用?type=henk3',
			//-----------------------------11X5---------------------
			'gd11x5'    => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=gd11x5&rows=20&format=json',
			'jx11x5'    => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=jx11x5&rows=20&format=json',
			'sh11x5'    => '自行看说明修复使用?type=sh11x5',
			'tj11x5'	=> '自行看说明修复使用?type=tj11x5',
			'zj11x5'	=> '自行看说明修复使用?type=zj11x5',
			'bj11x5'	=> '自行看说明修复使用?type=bj11x5',
			'yn11x5'	=> '自行看说明修复使用?type=yn11x5',
			'nmg11x5'	=> '自行看说明修复使用?type=nmg11x5',
			'gx11x5'	=> '自行看说明修复使用?type=gx11x5',
			'qh11x5'	=> '自行看说明修复使用?type=qh11x5',
			'shx11x5'	=> '自行看说明修复使用?type=shx11x5',
			'hen11x5'	=> '自行看说明修复使用?type=hen11x5',
			'gs11x5'	=> '自行看说明修复使用?type=gs11x5',
			'heb11x5'	=> '自行看说明修复使用?type=heb11x5',
			'hlj11x5'	=> '自行看说明修复使用?type=hlj11x5',
			'sd11x5'	=> '自行看说明修复使用?type=sd11x5',
			'xj11x5'	=> '自行看说明修复使用?type=xj11x5',
			'js11x5'	=> '自行看说明修复使用?type=js11x5',
			'fj11x5'	=> '自行看说明修复使用?type=fj11x5',
			'ah11x5'	=> '自行看说明修复使用?type=ah11x5',
			'hub11x5'	=> '自行看说明修复使用?type=hub11x5',
			'jl11x5'	=> '自行看说明修复使用?type=jl11x5',
			'sx11x5'	=> '自行看说明修复使用?type=sx11x5',
			'ln11x5'	=> '自行看说明修复使用?type=ln11x5',
			//-----------------------------X5  END-----------------------
			'gdkl10f'    => '/api.open.kj.code.gdkl10f',
			'tjkl10f'    => '/api.open.kj.code.tjkl10f',
			'cqkl10f'    => '/api.open.kj.code.cqkl10f',
			'bjpk10'     => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=bjpk10&rows=20&format=json',
			'txssc'     => '自行看说明修复使用?type=txffc',
			'lhc'     => '自行看说明修复使用?type=lhc',
			'fc3d'      => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=fc3d&rows=20&format=json',
			'pl3'       => 'http://wd.apiplus.net/newly.do?token=t3bb1c3dd2a286f16k&code=pl3&rows=20&format=json',
			'xyft'       => '自行看说明修复使用?type=xyft',
			'ynwfc'    => '/api.open.kj.code.ynwfc',
			'ynffc'    => '/api.open.kj.code.ynffc',
			'hnwfc'    => '/api.open.kj.code.hnwfc',
			'hnffc'    => '/api.open.kj.code.hnffc',

		];
